<div class="row">
<?php if (count($this->entities) > 0): ?>
    <?php
    echo $this->partial($this->pagingTemplate, array('currentPage' => $this->currentPage, 'totalPages' => $this->totalPages));
    ?>

    <div class="span12">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                <?php foreach ($this->fields as $fieldName => $label): ?>
                    <th>
                        <?php
                            $sortable = in_array($fieldName, $this->sortableFields);
                            $sortOrder = array_key_exists($fieldName, $this->currentSorting) && $this->currentSorting[$fieldName] === 'asc'
                                ? 'desc'
                                : 'asc';
                        ?>
                        <?php if ($sortable): ?>
                            <a href="<?php echo $this->readPage($this->currentPage, $fieldName, $sortOrder); ?>">
                        <?php endif; ?>
                        <?php echo $label; ?>
                        <?php if ($sortable): ?>
                            </a>
                        <?php endif; ?>
                    </th>
                <?php endforeach; ?>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->entities as $entity): ?>
                <tr>
                    <?php foreach ($entity as $value): ?>
                    <td><?php echo $value; ?></td>
                    <?php endforeach; ?>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <?php echo $this->partial($this->pagingTemplate, array('currentPage' => $this->currentPage, 'totalPages' => $this->totalPages)); ?>
<?php else: ?>
    <div class="span12">
        <p><?php echo $this->translate('There is nothing yet in the database!'); ?></p>
    </div>
<?php endif; ?>
</div>